export const APP_ID = "what2study";
export const KEY = "";
export const SERVER_URL= "http://localhost:1349/what2study/parse";
export const SERVER_URL_ ="https://www.cpstech.de/what2study/parse";
export const ServerCrawl_ ="https://www.cpstech.de/crawl/";
export const ServerCrawl ="http://127.0.0.1:5000/crawl";
export const SERVER_URL_parsefunctions_="https://www.cpstech.de/functions";
export const SERVER_URL_parsefunctions ="http://localhost:1349/what2study/parse/functions";
export const yellowMarkerBase64 = "https://raw.githubusercontent.com/pointhi/leaflet-color-markers/master/img/marker-icon-gold.png"
export const blackMarkerBase64 ="https://raw.githubusercontent.com/pointhi/leaflet-color-markers/master/img/marker-icon-black.png"
export const blueMarkerBase64 ="https://raw.githubusercontent.com/pointhi/leaflet-color-markers/master/img/marker-icon-blue.png"
export const greenMarkerBase64="https://raw.githubusercontent.com/pointhi/leaflet-color-markers/master/img/marker-icon-green.png"
